### ISSUE TITLE
Queue Url Stored as `object Object` in ENV

### ISSUE THREAD

**Issue by NimishVerma** [getlift/lift#106] opened 2021-09-27 14:09 UTC
The environment variable being exposed to the functions using the reference ${construct:myQueue.queueUrl} is being logged as '[object Object]'. That is a string, not even an object that I can parse/print using utils.

**Comment by mnapoli** [comment] 2021-10-01 11:48
Could you provide more details? For example `serverless.yml`, and which commands you're having problems with?

If this is with any local command, it may duplicate #93

**Comment by exaltedcelestial** [comment] 2021-10-01 11:53
It happens when you use `serverless-offline`

**Comment by mnapoli** [comment] 2021-10-01 11:54
OK, closing as duplicate of #93 then. Thank you for the update!

**Closed by mnapoli** 2021-10-01 11:54 UTC
