### ISSUE TITLE
Serverless Error occuring during a frontend deployment due to an exceeding number of build file to be deleted in Cloudfront S3

### ISSUE THREAD

**Issue by StanHannebelle** [getlift/lift#98] opened 2021-09-15 15:56 UTC
In my project, former build file are not automatically deleted in S3. This leads to an exceeding number of build files to delete during a deployment. When the number of file gets to high, the following error occurs:

![image](https://user-images.githubusercontent.com/45121661/133466524-3519c902-a45f-4693-8acf-396c11d35a68.png)

It can be manually resolved by manually deleting build files in S3.

**Comment by fredericbarthelet** [comment] 2021-09-16 09:45
Thanks @StanHannebelle for reporting this. Let's have a look together this afternoon and find out what the problem is :) Will update on this issue once we found the cause.

**Comment by mnapoli** [comment] 2021-09-16 09:48
Oh I wrote an answer yesterday but it seems like I forgot to press "send".

If I understand correctly, there are many files to delete. I suspect a solution could be to split "S3 deletes" in batches here:

https://github.com/getlift/lift/blob/449d23b4bdb3c06332d8df3a822784826835b5f2/src/utils/s3-sync.ts#L150-L159

**Comment by mnapoli** [comment] 2024-08-31 14:03
Fixed in #400

**Closed by mnapoli** 2024-08-31 14:03 UTC
Labels: bug
